# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.10.14                # https://pyreadiness.org/3.10
  - wheel=0.43.0
  - setuptools=69.2.0
  - pip=24.0                    # https://pip.pypa.io/en/stable/news
  - robocorp-truststore=0.8.0     # https://pypi.org/project/robocorp-truststore/
  - pandas=2.2.2
  - pip:
    - rpaframework==28.5.1        # https://rpaframework.org/releasenotes.html
    - robocorp==2.0.2             # https://pypi.org/project/robocorp
    - robocorp-browser==2.3.3     # https://pypi.org/project/robocorp-browser
    - pillow==10.3.0
